# Generated by Django 6.0.3 on 2026-05-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], default='RUNNING', max_length=10)),
                ('invoice_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='XeroConnection',
            fields=[
                ('tenant_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('tenant_name', models.CharField(blank=True, max_length=255)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expires_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpenInvoiceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=64)),
                ('invoice_id', models.CharField(max_length=64)),
                ('invoice_number', models.CharField(blank=True, max_length=64)),
                ('contact_id', models.CharField(db_index=True, max_length=64)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.CharField(blank=True, max_length=255)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('days_past_due', models.IntegerField(default=0)),
                ('bucket', models.CharField(max_length=20)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('status', models.CharField(max_length=20)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'bucket'], name='xero_app_op_tenant__cdcfb5_idx'), models.Index(fields=['tenant_id', 'contact_id'], name='xero_app_op_tenant__6982f5_idx')],
                'unique_together': {('tenant_id', 'invoice_id')},
            },
        ),
    ]
