# Generated by Django 6.0.3 on 2026-05-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=64)),
                ('invoice_id', models.CharField(max_length=64)),
                ('invoice_number', models.CharField(blank=True, max_length=64)),
                ('contact_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.CharField(blank=True, max_length=255)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('updated_date_utc', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-due_date', '-invoice_date'],
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='xero_app_in_tenant__a75bf5_idx'), models.Index(fields=['tenant_id', 'due_date'], name='xero_app_in_tenant__3dac15_idx')],
                'unique_together': {('tenant_id', 'invoice_id')},
            },
        ),
    ]
