# Generated by Django 6.0.3 on 2026-05-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_app', '0002_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='xeroconnection',
            name='invoices_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
