# Generated by Django 6.0.3 on 2026-05-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_app', '0003_xeroconnection_invoices_synced_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=64)),
                ('invoice_id', models.CharField(max_length=64)),
                ('events_json', models.TextField(blank=True, default='[]')),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('tenant_id', 'invoice_id')},
            },
        ),
    ]
