# Generated by Django 6.0.3 on 2026-05-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_app', '0004_invoicehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedDebtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=64)),
                ('contact_id', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('closed_by', models.CharField(blank=True, max_length=255)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-closed_at'],
                'unique_together': {('tenant_id', 'contact_id')},
            },
        ),
    ]
