# Generated by Django 6.0.3 on 2026-05-28 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_app', '0006_contactdetail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtorAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=64)),
                ('contact_id', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('assigned_by', models.CharField(blank=True, max_length=255)),
                ('assigned_at', models.DateTimeField(auto_now=True)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_debtors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tenant_id', 'contact_id')},
            },
        ),
    ]
