# Generated by Django 6.0.3 on 2026-05-28 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_app', '0008_invoicecomment_invoicecommentattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=64)),
                ('contact_id', models.CharField(db_index=True, max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('called_by_name', models.CharField(blank=True, max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('called_at', models.DateTimeField(auto_now_add=True)),
                ('called_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls_logged', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-called_at'],
            },
        ),
    ]
