# Generated by Django 6.0.3 on 2026-05-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_app', '0009_calllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='invoice_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='calllog',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
