# Generated by Django 6.0.3 on 2026-05-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_app', '0010_calllog_invoice_id_calllog_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinvoicesnapshot',
            name='last_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openinvoicesnapshot',
            name='last_reminder_stage',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='openinvoicesnapshot',
            name='project_code',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='syncrun',
            name='api_calls',
            field=models.IntegerField(default=0),
        ),
    ]
