# Generated by Django 6.0.3 on 2026-06-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_app', '0011_openinvoicesnapshot_last_reminder_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteOffInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=64)),
                ('invoice_id', models.CharField(db_index=True, max_length=64)),
                ('invoice_number', models.CharField(blank=True, max_length=64)),
                ('contact_id', models.CharField(blank=True, max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('written_off_by', models.CharField(blank=True, max_length=255)),
                ('written_off_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-written_off_at'],
                'unique_together': {('tenant_id', 'invoice_id')},
            },
        ),
    ]
