# Generated by Django 6.0.3 on 2026-06-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_app', '0012_writeoffinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('mode', models.CharField(choices=[('interval', 'Every N hours'), ('fixed', 'At specific times of day')], default='interval', max_length=10)),
                ('interval_hours', models.IntegerField(default=1)),
                ('fixed_times', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
