# Generated by Django 6.0.3 on 2026-06-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_app', '0013_syncschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoverExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=64)),
                ('contact_id', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('excluded_by', models.CharField(blank=True, max_length=255)),
                ('excluded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-excluded_at'],
                'unique_together': {('tenant_id', 'contact_id')},
            },
        ),
        migrations.CreateModel(
            name='HandoverInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=64)),
                ('invoice_id', models.CharField(db_index=True, max_length=64)),
                ('invoice_number', models.CharField(blank=True, max_length=64)),
                ('contact_id', models.CharField(blank=True, max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('auto', 'Auto (>65 days)'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('marked_by', models.CharField(blank=True, max_length=255)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('activated_for_lawyer', models.BooleanField(default=False)),
                ('activated_by', models.CharField(blank=True, max_length=255)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-marked_at'],
                'unique_together': {('tenant_id', 'invoice_id')},
            },
        ),
    ]
