# Generated by Django 6.0.3 on 2026-06-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_app', '0015_whatsapptemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinvoicesnapshot',
            name='inspector',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='openinvoicesnapshot',
            name='online_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='OnlineInvoiceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=64)),
                ('invoice_id', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=255)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('tenant_id', 'invoice_id')},
            },
        ),
    ]
