# Generated by Django 6.0.3 on 2026-06-09 14:27

from django.db import migrations, models


def retag_whatsapp_calllogs(apps, schema_editor):
    """Historical WhatsApp reminders were stored as CallLog rows with a note
    beginning 'WhatsApp reminder sent'. Retag them so they count toward the
    WhatsApp channel (and no longer suppress the separate Call prompt)."""
    CallLog = apps.get_model('xero_app', 'CallLog')
    CallLog.objects.filter(note__startswith='WhatsApp').update(action_type='whatsapp')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('xero_app', '0016_openinvoicesnapshot_inspector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_text', models.TextField(blank=True, default='')),
                ('body_text', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='calllog',
            name='action_type',
            field=models.CharField(choices=[('call', 'Call'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], db_index=True, default='call', max_length=10),
        ),
        migrations.RunPython(retag_whatsapp_calllogs, noop_reverse),
    ]
