# Generated by Django 6.0.3 on 2026-06-09 19:15

from django.db import migrations, models


def seed_default_templates(apps, schema_editor):
    """Seed the first default template per channel from the previous single-row
    WhatsAppTemplate / EmailTemplate (falling back to the module defaults), so the
    new multi-template system starts with the wording the site already used."""
    from xero_app.models import (DEFAULT_WA_TEMPLATE, DEFAULT_EMAIL_SUBJECT,
                                 DEFAULT_EMAIL_BODY)
    MessageTemplate = apps.get_model('xero_app', 'MessageTemplate')
    WhatsAppTemplate = apps.get_model('xero_app', 'WhatsAppTemplate')
    EmailTemplate = apps.get_model('xero_app', 'EmailTemplate')

    if not MessageTemplate.objects.filter(channel='whatsapp').exists():
        wa = WhatsAppTemplate.objects.first()
        body = (wa.template_text if wa and wa.template_text else DEFAULT_WA_TEMPLATE)
        MessageTemplate.objects.create(
            channel='whatsapp', name='Standard reminder', body=body,
            is_default=True, sort_order=0)

    if not MessageTemplate.objects.filter(channel='email').exists():
        em = EmailTemplate.objects.first()
        subject = (em.subject_text if em and em.subject_text else DEFAULT_EMAIL_SUBJECT)
        body = (em.body_text if em and em.body_text else DEFAULT_EMAIL_BODY)
        MessageTemplate.objects.create(
            channel='email', name='Standard reminder', subject=subject, body=body,
            is_default=True, sort_order=0)


def unseed(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('xero_app', '0017_emailtemplate_calllog_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], db_index=True, max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('subject', models.TextField(blank=True, default='')),
                ('body', models.TextField(blank=True, default='')),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['channel', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('go_live_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.RunPython(seed_default_templates, unseed),
    ]
