# Generated by Django 6.0.3 on 2026-06-09 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_exclusions(apps, schema_editor):
    """Carry the old binary HandoverExclusion rows over to HandoverSetting with
    auto_handover=False (never auto-hand over) so existing arrangements survive."""
    HandoverExclusion = apps.get_model('xero_app', 'HandoverExclusion')
    HandoverSetting = apps.get_model('xero_app', 'HandoverSetting')
    for ex in HandoverExclusion.objects.all():
        HandoverSetting.objects.update_or_create(
            tenant_id=ex.tenant_id, contact_id=ex.contact_id,
            defaults={"contact_name": ex.contact_name, "auto_handover": False,
                      "handover_days": 65, "note": ex.note or "",
                      "set_by": ex.excluded_by or ""},
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('xero_app', '0018_messagetemplate_systemsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoverSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=64)),
                ('contact_id', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('auto_handover', models.BooleanField(default=True)),
                ('handover_days', models.IntegerField(default=65)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('set_by', models.CharField(blank=True, max_length=255)),
                ('set_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['contact_name'],
                'unique_together': {('tenant_id', 'contact_id')},
            },
        ),
        migrations.CreateModel(
            name='LegalMatter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=64)),
                ('contact_id', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('active', 'Active'), ('closed', 'Closed')], db_index=True, default='pending', max_length=10)),
                ('track', models.CharField(blank=True, default='', max_length=20)),
                ('opposed', models.BooleanField(default=False)),
                ('sent_by', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.CharField(blank=True, max_length=255)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('tenant_id', 'contact_id')},
            },
        ),
        migrations.CreateModel(
            name='LegalStepComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_key', models.CharField(db_index=True, max_length=60)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_step_comments', to=settings.AUTH_USER_MODEL)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_comments', to='xero_app.legalmatter')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_key', models.CharField(max_length=60)),
                ('done', models.BooleanField(default=False)),
                ('done_by', models.CharField(blank=True, max_length=255)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_states', to='xero_app.legalmatter')),
            ],
            options={
                'unique_together': {('matter', 'step_key')},
            },
        ),
        migrations.RunPython(migrate_exclusions, noop),
    ]
