# Generated by Django 6.0.3 on 2026-06-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_app', '0019_handoversetting_legalmatter_legalstepcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalmatter',
            name='application_opposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legalmatter',
            name='summons_opposed',
            field=models.BooleanField(default=False),
        ),
    ]
