# Generated by Django 6.0.3 on 2026-06-10 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_app', '0020_legalmatter_application_opposed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveredInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=64)),
                ('invoice_id', models.CharField(db_index=True, max_length=64)),
                ('invoice_number', models.CharField(blank=True, max_length=64)),
                ('contact_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credited', models.BooleanField(db_index=True, default=False)),
                ('administrator_name', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(choices=[('collected', 'Collected by admin'), ('handover_legal', 'In handover / with lawyers'), ('no_followup', 'No follow-up logged'), ('unallocated', 'Debtor not allocated')], default='collected', max_length=20)),
                ('days_past_due', models.IntegerField(default=0)),
                ('recovered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('administrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recoveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recovered_at'],
                'indexes': [models.Index(fields=['tenant_id', 'administrator', 'recovered_at'], name='xero_app_re_tenant__c70132_idx')],
            },
        ),
    ]
