# Generated by Django 6.0.3 on 2026-06-10 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_app', '0021_recoveredinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoversetting',
            name='cadence_shift_days',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LegalStepCommentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='legal_comments/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='xero_app.legalstepcomment')),
            ],
        ),
    ]
