# Generated by Django 6.0.3 on 2026-06-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_app', '0022_handoversetting_cadence_shift_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoveredinvoice',
            name='reason',
            field=models.CharField(choices=[('collected', 'Collected by admin'), ('collected_legal', 'Recovered while with the lawyers'), ('handover_legal', 'In handover (pre-lawyers)'), ('no_followup', 'No follow-up logged'), ('unallocated', 'Debtor not allocated')], default='collected', max_length=20),
        ),
    ]
