# Generated by Django 6.0.3 on 2026-06-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_app', '0023_alter_recoveredinvoice_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerReportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('daily', 'Every day'), ('weekly', 'Every week'), ('fortnightly', 'Every 2 weeks'), ('monthly', 'Every month')], default='weekly', max_length=12)),
                ('day_of_week', models.IntegerField(default=0)),
                ('day_of_month', models.IntegerField(default=1)),
                ('send_hour', models.IntegerField(default=7)),
                ('send_minute', models.IntegerField(default=0)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ReportRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
    ]
