# Generated by Django 6.0.3 on 2026-06-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_app', '0024_lawyerreportconfig_reportrecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicecommentattachment',
            name='nature',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='legalstepcommentattachment',
            name='nature',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
