# Generated by Django 6.0.3 on 2026-06-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('administrator', 'Administrator'), ('inspector', 'Inspector'), ('lawyer', 'Lawyer')], default='inspector', max_length=20),
        ),
    ]
