# Generated by Django 6.0.3 on 2026-06-19 06:54

from django.db import migrations, models


def clear_inspector_users(apps, schema_editor):
    """The Inspector role has been removed. Any existing inspector users lose
    their role (no access) and are deactivated, so nothing is left referencing
    the removed role. Reversible: reactivate and assign a real role."""
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role='inspector').update(role='', is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('administrator', 'Administrator'), ('lawyer', 'Lawyer')], default='', max_length=20),
        ),
        migrations.RunPython(clear_inspector_users, migrations.RunPython.noop),
    ]
